[zh]
    languageCode      = "zh-cn"
    languageName      = "中文"
    languagedirection = "ltr"
    title             = "LKWLhsy"
    weight            = 1

[en]
    languageCode      = "en-us"
    languageName      = "English"
    languagedirection = "ltr"
    title             = "LKWLhsy"
    weight            = 2
    disabled          = true
