# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/me.jpg"

# Accepted values: "default", "lastmod"
SortBy              = "default"

[footer]
    copyrightText      = "© {year} {title}"
    runtimeIcon        = "🚀"
    runtimeLoadingText = "Calculating site runtime..."
    runtimeText        = "Running for {days} days {hours} hours {minutes} minutes"
    customText         = "Custom footer content"
    poweredByText      = "Built with <a href=\"https://gohugo.io/\" target=\"_blank\" rel=\"noopener\">Hugo</a> | Theme <b><a href=\"https://github.com/CaiJimmy/hugo-theme-stack\" target=\"_blank\" rel=\"noopener\">Stack</a></b> designed by <a href=\"https://jimmycai.com\" target=\"_blank\" rel=\"noopener\">Jimmy</a>"

[dateFormat]
    published   = ":date_medium"
    lastUpdated = ":date_medium"

[sidebar]
    emoji    = "🚀"
    subtitle = "An starter template based on Hugo Theme Stack v4"
    avatar   = "img/me.jpg"

[article]
    headingAnchor = true
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"
