# 内容所在的子目录，将显示在首页和归档页
mainSections = ["post"]
# 在 RSS 中输出全文
rssFullContent = true
favicon        = "img/me.jpg"

# 排序方式: "default", "lastmod"
SortBy              = "default"

[footer]
    copyrightText    = "© {year} {title}"
    runtimeIcon      = "🚀"
    runtimeLoadingText = "正在计算运行时间..."
    runtimeText      = "已运行 {days} 天 {hours} 时 {minutes} 分"
    customText       = " "
    poweredByText    = "主题 <b><a href=\"https://github.com/CaiJimmy/hugo-theme-stack\" target=\"_blank\" rel=\"noopener\">Stack</a></b> 由 <a href=\"https://jimmycai.com\" target=\"_blank\" rel=\"noopener\">Jimmy</a> 设计"

[dateFormat]
    # 使用当地日期格式
    published   = ":date_medium"
    lastUpdated = ":date_medium"

[sidebar]
    emoji    = "^_^"
    subtitle = "如果你不仅见过这个世界，还见过一些其他世界的东西，那么便算是真正的活过。"
    avatar   = "img/me.jpg"

[article]
    headingAnchor = true
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "采用 CC BY-NC-SA 4.0 许可协议"
